version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: gym-https-portal
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
    # 動作確認は'staging'で、本番時は'production'
    # 'production'で試行錯誤するとすぐにrate-limitにかかる
      STAGE: 'staging'
      DOMAINS: >-
        www.giraffegiraffegiraffe.tokyo -> http://gym-progress-docker_app:80
    volumes:
    - sample-vhosts:/var/www/vhosts
  web:
    build: ./line-bot
    container_name: gym-progress-docker_app
    restart: always
    env_file:
      - ./secret.env
volumes:
  sample-vhosts:
